# Generated by Django 4.1 on 2022-08-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_movie_glass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glass',
            old_name='year',
            new_name='costo',
        ),
        migrations.RenameField(
            model_name='glass',
            old_name='title',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='glass',
            name='desc',
        ),
        migrations.AlterField(
            model_name='glass',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
